use_frameworks!

platform :ios, '10.3'

target 'Apple-Cocoapod-KochavaConsent_Example' do
  pod 'Apple-Cocoapod-KochavaConsent', :path => '../'

  target 'Apple-Cocoapod-KochavaConsent_Tests' do
    inherit! :search_paths

    
  end
end
